name: GitHub 2048 CI/CD
on: [push]
jobs:
  Compile:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
      - run: mvn compile
      - run: mkdir staging && cp target/*.war staging
      - uses: actions/upload-artifact@v3
        with:
          name: Package
          path: staging