name: GitHub 2048 CI/CD
on: [ push ]
jobs:
  compile-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: 'maven'
      - run: mvn compile
      - uses: actions/upload-artifact@v3
        with:
          name: classes
          path: /home/runner/work/CI-CD-2048/CI-CD-2048/target/classes
  test-job:
    needs: compile-job
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: 'maven'
      - name: download artifacts
        uses: actions/download-artifact@v3
        with:
          name: classes
      - run: mvn test
  package-job:
    needs: compile-job
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: 'maven'
      - name: download artifacts
        uses: actions/download-artifact@v3
        with:
          name: classes
      - run: mvn package
      - uses: actions/upload-artifact@v3
        with:
          name: package
          path: /home/runner/work/CI-CD-2048/CI-CD-2048/target/game2048.war
  deploy-job:
    needs: [package-job]
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: 'maven'
      - name: download artifacts
        uses: actions/download-artifact@v3
        with:
          name: package
      - name: deploy war to tomcat
        run: |
          COPY ./game2048.war /usr/local/tomcat/webapps