name: GitHub 2048 CI/CD
on: [push]
jobs:
  Compile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: 'maven
      - run: mvn compile
      - run: mkdir artifacts && cp target/*.class artifacts
      - uses: actions/upload-artifact@v3
        with:
          name: classes
          path: artifacts
      - run: mvn test
      - run: mvn package